package org.eyematics.process.constant;

public interface InitiateConstants {

    String PROCESS_NAME_EXECUTE_INITIATE_EYEMATICS_PROCESS = "eyematicsInitiateProcess";
    String PROCESS_NAME_FULL_EXECUTE_INITIATE_EYEMATICS_PROCESS =  EyeMaticsConstants.PROCESS_EYEMATICS_NAME_BASE + PROCESS_NAME_EXECUTE_INITIATE_EYEMATICS_PROCESS;

    String BPMN_RECEIVE_EXECUTION_VARIABLE_SELECTED_PROVIDE_TARGETS = "selectedProvideTargets";
    String BPMN_RECEIVE_EXECUTION_VARIABLE_INITIATE_RECEIVE_QUEUE = "initiateReceiveQueue";

}
