package org.eyematics.process.constant;

public interface ProvideConstants {

    String PROCESS_NAME_EXECUTE_PROVIDE_EYEMATICS_PROCESS = "eyematicsProvideProcess";
    String PROCESS_NAME_FULL_EXECUTE_PROVIDE_EYEMATICS_PROCESS =  EyeMaticsConstants.PROCESS_EYEMATICS_NAME_BASE + PROCESS_NAME_EXECUTE_PROVIDE_EYEMATICS_PROCESS;

    String BPMN_PROVIDE_EXECUTION_VARIABLE_DATA_SET_ENCRYPTED = "dataSetEncrypted";
    String BPMN_PROVIDE_EXECUTION_VARIABLE_DATA_SET = "dataSet";
    String BPMN_PROVIDE_EXECUTION_VARIABLE_DATA_SET_REFERENCE = "data-reference";

    String BPMN_PROVIDE_EXECUTION_VARIABLE_DATA_ERROR = "dataProvideError";
    String BPMN_PROVIDE_EXECUTION_VARIABLE_DATA_ERROR_MESSAGE = "dataProvideErrorMessage";
}
