package org.eyematics.process.constant;


public interface ProvideConstants {
    String PROCESS_NAME_EXECUTE_PROVIDE_EYEMATICS_PROCESS = "eyematicsProvideProcess";
    String PROCESS_NAME_FULL_EXECUTE_PROVIDE_EYEMATICS_PROCESS =  EyeMaticsConstants.PROCESS_EYEMATICS_NAME_BASE + PROCESS_NAME_EXECUTE_PROVIDE_EYEMATICS_PROCESS;

    String BPMN_EXECUTION_VARIABLE_EYEMATICS_DATA_SET_ADMIN_APPROVAL_REQUIRED = "eyematicsDataSetAdminApprovalRequired";
    String BPMN_EXECUTION_VARIABLE_EYEMATICS_DATA_SET_ADMIN_APPROVED = "eyematicsDataSetAdminApproved";

    String BPMN_PROVIDE_EXECUTION_VARIABLE_PATIENT_DATA_SET = "patientDataSet";
    String BPMN_PROVIDE_EXECUTION_VARIABLE_MEASURE_REPORT_DATA_SET = "measureReportDataSet";
    String BPMN_PROVIDE_EXECUTION_VARIABLE_MEDICATION_DATA_SET = "medicationDataSet";
    String BPMN_PROVIDE_EXECUTION_VARIABLE_OBSERVATION_DATA_SET = "observationDataSet";
    String BPMN_PROVIDE_EXECUTION_VARIABLE_DIAGNOSTIC_REPORT_DATA_SET = "diagnosticReportDataSet";
    String BPMN_PROVIDE_EXECUTION_VARIABLE_MEDICATION_ADMINISTRATION_DATA_SET = "medicationAdministrationDataSet";
    String BPMN_PROVIDE_EXECUTION_VARIABLE_MEDICATION_REQUEST_DATA_SET = "medicationRequestDataSet";
    String BPMN_PROVIDE_EXECUTION_VARIABLE_ORGANIZATION_DATA_SET = "organizationDataSet";


    String BPMN_PROVIDE_EXECUTION_VARIABLE_DATA_SET = "dataSet";
    String BPMN_PROVIDE_EXECUTION_VARIABLE_DATA_SET_REFERENCE_BUNDLE = "dataSetReferenceBundle";
    String BPMN_PROVIDE_EXECUTION_VARIABLE_GLOBAL_PSEUDONYMS = "globalPseudonyms";

    String PROFILE_TASK_EYEMATICS_PROVIDE_PROCESS_URI = EyeMaticsConstants.PROCESS_EYEMATICS_URI_BASE + PROCESS_NAME_EXECUTE_PROVIDE_EYEMATICS_PROCESS;
    String PROFILE_TASK_EYEMATICS_PROVIDE_PROCESS = "https://eyematics.org/fhir/StructureDefinition/eyematics-provide-process-structure-definition";
    String PROFILE_TASK_EYEMATICS_PROVIDE_PROCESS_MESSAGE_NAME = "provideProcessStartEventMessage";
    String PROFILE_TASK_EYEMATICS_PROVIDE_PROCESS_ACKNOWLEDGEMENT = "https://eyematics.org/fhir/StructureDefinition/eyematics-provide-process-acknowledgement-structure-definition";
    String PROFILE_TASK_EYEMATICS_PROVIDE_PROCESS_ACKNOWLEDGEMENT_MESSAGE_NAME = "provideProcessAcknowledgementEventMessage";

    int MINIMUM_PAGE_FHIR_PER_QUERY_SIZE = 50;
    int MAXIMUM_PAGE_FHIR_PER_QUERY_SIZE = 1000;

    int MINIMUM_PAGE_FHIR_PER_FTTP_REQUEST = 10;
    int MAXIMUM_PAGE_FHIR_PER_FTTP_REQUEST = 100;

    int MINIMUM_NUMBER_OF_PATIENTS_PER_BUNDLE = 1;
    int MAXIMUM_NUMBER_OF_PATIENTS_PER_BUNDLE = 1000;

    String BPMN_PROVIDE_EXECUTION_VARIABLE_ACKNOWLEDGEMENT_WAITING_DURATION = "acknowledgementWaitingDuration";
    long MINIMUM_ACKNOWLEDGEMENT_WAITING_DURATION_PER_PATIENT = 5;
    long MAXIMUM_ACKNOWLEDGEMENT_WAITING_DURATION_PER_PATIENT = 60;
}
